server:
  port: 8080
  servlet:
    context-path: /demo
spring:
  rabbitmq:
    host: 192.168.2.65
    port: 5672
    username: mqadmin
    password: mqadmin
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1 #每次处理1条消息
        retry.max-attempts: 3 # 最大重试次数
        retry.enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
        retry.initial-interval: 2000 #重试间隔时间（单位毫秒）
        default-requeue-rejected: true #该
      direct:
        acknowledge-mode: manual
        prefetch: 1 #每次处理1条消息
        retry.max-attempts: 3 # 最大重试次数
        retry.enabled: true #是否开启消费者重试（为false时关闭消费者重试，这时消费端代码异常会一直重复收到消息）
        retry.initial-interval: 2000 #重试间隔时间（单位毫秒）
        default-requeue-rejected: true #该配置项是决定由于监听器抛出异常而拒绝的消息是否被重新放回队列。默认值为true,需要手动basicNack时这些参数谅失效了
